In [3]:
# 1:
import pandas as pd

movies = pd.DataFrame({
    "title": ["3 Idiots", "Dangal", "Zindagi Na Milegi Dobara", "Taare Zameen Par", "PK", "Sholay"],
    "rating": [8.4, 8.3, 8.2, 8.3, 8.1, 8.1],
    "release_year": [2009, 2016, 2011, 2007, 2014, 1975]
})

movies.sort_values(by="rating", ascending=False)

                      title  rating  release_year
0                  3 Idiots     8.4          2009
1                    Dangal     8.3          2016
3          Taare Zameen Par     8.3          2007
2  Zindagi Na Milegi Dobara     8.2          2011
4                        PK     8.1          2014
5                    Sholay     8.1          1975

In [4]:
# 2:
ipl = pd.DataFrame({
    "team": ["CSK", "MI", "RCB", "KKR", "RR"],
    "points": [16, 18, 14, 12, 10],
    "net_run_rate": [0.45, 0.75, 0.25, 0.10, -0.20]
})

ipl.sort_index(ascending=False)

  team  points  net_run_rate
4   RR      10         -0.20
3  KKR      12          0.10
2  RCB      14          0.25
1   MI      18          0.75
0  CSK      16          0.45

In [10]:
# 3:
videos = pd.DataFrame({
    "video_title": ["Funny Cat Video", "New Song", "Cricket Highlights", "Travel Vlog", "Comedy Video"],
    "views": [5000000, 8000000, 3000000, 2000000, 6000000],
    "likes": [400000, 700000, 250000, 150000, 500000]
})

videos.index = [5, 8, 12, 15, 20]

In [11]:
print("Before resetting index:")
print(videos)

Before resetting index:
           video_title    views   likes
5      Funny Cat Video  5000000  400000
8             New Song  8000000  700000
12  Cricket Highlights  3000000  250000
15         Travel Vlog  2000000  150000
20        Comedy Video  6000000  500000

In [12]:
videos = videos.reset_index(drop=True)

In [9]:
videos

          video_title    views   likes
0     Funny Cat Video  5000000  400000
1            New Song  8000000  700000
2  Cricket Highlights  3000000  250000
3         Travel Vlog  2000000  150000
4        Comedy Video  6000000  500000

In [17]:
# 4:
restaurants = pd.DataFrame({
    "restaurant": ["Pizza Hut", "Dominos", "Biryani Blues", "Burger King", "Haldiram"],
    "rating": [4.5, 4.2, 4.3, 4.1, 4.4]
})

print("Original DataFrame:")
print(restaurants)

Original DataFrame:
      restaurant  rating
0      Pizza Hut     4.5
1        Dominos     4.2
2  Biryani Blues     4.3
3    Burger King     4.1
4       Haldiram     4.4

In [22]:
restaurants = restaurants.reindex([2, 0, 1, 3, 4])

In [23]:
print("After reindexing:")
print(restaurants)

After reindexing:
      restaurant  rating
2  Biryani Blues     4.3
0      Pizza Hut     4.5
1        Dominos     4.2
3    Burger King     4.1
4       Haldiram     4.4

In [24]:
# 5:
products = pd.DataFrame({
    "product_name": ["Mobile", "Laptop", "Headphones", "Watch", "Tablet"],
    "price": [15000, 50000, 2000, 3000, 20000],
    "discount": [10, 30, 50, 20, 40]
})

In [25]:
print("Original DataFrame:")
print(products)

Original DataFrame:
  product_name  price  discount
0       Mobile  15000        10
1       Laptop  50000        30
2   Headphones   2000        50
3        Watch   3000        20
4       Tablet  20000        40

In [26]:
products = products.sort_values(by="discount", ascending=False)

In [27]:
products = products.reset_index(drop=True)

In [28]:
print("After sorting and resetting index:")
print(products)

After sorting and resetting index:
  product_name  price  discount
0   Headphones   2000        50
1       Tablet  20000        40
2       Laptop  50000        30
3        Watch   3000        20
4       Mobile  15000        10